---
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix, "lf"]
      # - id: no-commit-to-branch
      #   args: [--branch, main, --branch, master, --branch, devel]
      - id: trailing-whitespace
  # - repo: https://gitlab.com/smop/pre-commit-hooks
  #   rev: "v1.0.0"
  #   hooks:
  #     - id: check-gitlab-ci
  # - repo: https://gitlab.com/devopshq/gitlab-ci-linter
  #   rev: "v1.0.6"
  #   hooks:
  #     - id: gitlab-ci-linter
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.27.0"
    hooks:
      - id: check-gitlab-ci
  # - repo: https://github.com/FalcoSuessgott/lint-gitlab-ci
  #   rev: "v0.0.6"
  #   hooks:
  #     - id: gitlab-ci
