---
# yamllint disable rule:line-length
name: CI

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    container:
      image: 'python:3.11.3-slim-bullseye'
    steps:
      - name: test 1
        run: python -c 'import time'
      - name: test 2
        run: python -c 'print("hello")'
      - name: test 3
        run: python -c 'import time; print(time)'
      - name: test 4
        run: python -c 'import time; print(f"{dir(time)}")'
      - name: test 5
        run: |
          python -c 'import time; print(f"{dir(time)}")'
